config/routes.rb
Rails.application.routes.draw do
  # "/"にアクセスがあった時に、アクセスしてきたブラウザの設定言語からリダイレクトを判断する
  root to: "application#redirect_by_locale"
  scope "(:locale)", locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    namespace :league_of_legends, path: "lol" do
      root to: "top#index"
      resources :summoners, only: %i[ create ] do
        resources :matches, only: %i[ index show ], module: "summoners"
      end
    end
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
    # Can be used by load balancers and uptime monitors to verify that the app is live.
    get "up" => "rails/health#show", as: :rails_health_check

    # Render dynamic PWA files from app/views/pwa/*
    get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
    get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

    # Defines the root path route ("/")
    # root "posts#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/summoner.rb
class Summoner < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # "/"にアクセスがあった時に、任意の言語のページにリダイレクトする処理
  def redirect_by_locale
    locale = extract_locale_from_accept_language_header || I18n.default_locale
    redirect_to "/#{locale}/lol"
  end

  private

  def switch_locale(&action)
    I18n.with_locale(locale, &action)
  end

  def locale
    @locale ||= params[:locale] || I18n.default_locale
  end

  # リクエストヘッダーからユーザーのロケールを推測して返す処理
  def extract_locale_from_accept_language_header
    lang = request.env["HTTP_ACCEPT_LANGUAGE"]&.scan(/^[a-z]{2}/)&.first
    I18n.available_locales.map(&:to_s).include?(lang) ? lang : nil
  end
end

app/controllers/league_of_legends/searched_players_controller.rb
class LeagueOfLegends::SummonersController < ApplicationController
  def create
  end
end

app/controllers/league_of_legends/summoners/matches_controller.rb
require "net/http"
require "uri"
require "json"

class LeagueOfLegends::Summoners::MatchesController < ApplicationController
  def index
    searched_summoner = Summoner.find(params[:summoner_id])
    puuid = searched_summoner.puuid

    # 入力されたサモナーの試合のリストを取得

    platform_routing_value = "na1.api.riotgames.com"
    platform = platform_routing_value.split(".").first
    regional_routing_value = "americas.api.riotgames.com"
    api = "/lol/match/v5/matches/by-puuid/#{puuid}/ids"
    uri = URI.parse("https://#{regional_routing_value}#{api}?count=5")
    request = Net::HTTP::Get.new(uri)
    request["X-Riot-Token"] = ENV["RIOT_DEVELOPMENT_API"]
    response_data = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) do |http|
      http.request(request)
    end
    matches_ids = JSON.parse(response_data.body)

    @matches = []

    # 各試合の詳細データを取得
    matches_ids.each do |match_id|
      api = "/lol/match/v5/matches/#{match_id}"
      uri = URI.parse("https://#{regional_routing_value}#{api}")
      request = Net::HTTP::Get.new(uri)
      request["X-Riot-Token"] = ENV["RIOT_DEVELOPMENT_API"]
      response_data = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) do |http|
        http.request(request)
      end
      match = JSON.parse(response_data.body)
      participant = match["info"]["participants"].find { |p| p["puuid"] == puuid }
      team_id = participant["teamId"]
      team_info = match["info"]["teams"].find { |team| team["teamId"] == team_id }

      @matches << {
        match: match,
        did_win: team_info["win"]
      }
    end
  end
end

app/controllers/league_of_legends/summoners_controller.rb
require "net/http"
require "uri"
require "json"

class LeagueOfLegends::SummonersController < ApplicationController
  def create
    name, tagline = summoners_params[:name].gsub(" ", "").split("#", 2)

    # 入力されたサモナーのpuuidの取得
    platform_routing_value = "na1.api.riotgames.com"
    platform = platform_routing_value.split(".").first
    regional_routing_value = "americas.api.riotgames.com"
    api = "/riot/account/v1/accounts/by-riot-id/#{name}/#{tagline}"
    uri = URI.parse("https://#{regional_routing_value}#{api}")
    request = Net::HTTP::Get.new(uri)
    request["X-Riot-Token"] = ENV["RIOT_DEVELOPMENT_API"]
    response_data = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) do |http|
      http.request(request)
    end
    summoner_data = JSON.parse(response_data.body)

    if Summoner.exists?(puuid: summoner_data["puuid"])
      summoner_id = Summoner.find_by(puuid: summoner_data["puuid"]).id
      redirect_to league_of_legends_summoner_matches_path(summoner_id: summoner_id)
    else
      summoner = Summoner.new({
                      name: summoner_data["gameName"],
                      tagline: summoner_data["tagLine"],
                      platform: platform,
                      puuid: summoner_data["puuid"]
                    })

      if summoner.save
        redirect_to league_of_legends_summoner_matches_path(summoner_id: summoner.id)
      end
    end
  end

  private

  def summoners_params
    params.require(:summoner).permit(:name)
  end
end

app/controllers/league_of_legends/top_controller.rb
class LeagueOfLegends::TopController < ApplicationController
  http_basic_authenticate_with(
    name: ENV["BASIC_AUTH_NAME"],
    password: ENV["BASIC_AUTH_PASSWORD"]
    )

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/league_of_legends/top_helper.rb
module LeagueOfLegends::TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ggreports" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/league_of_legends/summoners/matches/index.html.erb
<div>
  <div data-controller="match-card">
    <% @matches.each do |match| %>
      <% if match[:did_win] %>
        <div data-action="click->match-card#navigate">
          <div class="border border-black rounded-3xl text-green-300 p-2" match-id="<%= match[:match]["metadata"]["matchId"] %>">
            <%= match[:match]["info"]["gameMode"] %>
            Victory
          </div>
        </div>
      <% else %>
        <div data-action="click->match-card#navigate">
          <div class="border border-black rounded-3xl text-red-300 p-2" match-id="<%= match[:match]["metadata"]["matchId"] %>">
            <%= match[:match]["info"]["gameMode"] %>
            Defeat
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/league_of_legends/top/index.html.erb
<div>
  <div>Top Page</div>
  <div>
    <%= form_with url: league_of_legends_summoners_path, method: :post, scope: :summoner do |f| %>
      North America
      <%= f.text_field :name, placeholder: 'player name + #NA1' %>
      <%= f.submit 'search' %>
    <% end %>
  </div>
</div>